//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use super::sea_orm_active_enums::MempoolStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "mempool_transaction")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", unique)]
    pub txid: Vec<u8>,
    pub status: MempoolStatus,
    pub created_at: i64,
    pub sender: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::l1_transaction::Entity",
        from = "Column::Txid",
        to = "super::l1_transaction::Column::Txid",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    L1Transaction,
}

impl Related<super::l1_transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::L1Transaction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
