//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "spark_output")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub spark_id: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub tx_hash: Vec<u8>,
    pub vout: i32,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub token_pubkey: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub owner_pubkey: Vec<u8>,
    pub withdrawal_bond_sats: i32,
    pub withdrawal_locktime: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub exit_script: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub token_amount: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub revocation_pubkey: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub revocation_secret_key: Option<Vec<u8>>,
    pub is_frozen: Option<bool>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub withdraw_txid: Option<Vec<u8>>,
    pub withdraw_vout: Option<i32>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub withdraw_blockhash: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub spend_txid: Option<Vec<u8>>,
    pub spend_vout: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::spark_transaction::Entity",
        from = "Column::TxHash",
        to = "super::spark_transaction::Column::TxHash",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SparkTransaction,
}

impl Related<super::spark_transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SparkTransaction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
