//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "spark_burn")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub tx_hash: Vec<u8>,
    pub vout: i32,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub token_pubkey: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub amount: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::spark_transaction::Entity",
        from = "Column::TxHash",
        to = "super::spark_transaction::Column::TxHash",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SparkTransaction,
}

impl Related<super::spark_transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SparkTransaction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
