//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use super::sea_orm_active_enums::SignatureType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user_signature")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub tx_hash: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub signature: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub operator_public_key: Option<Vec<u8>>,
    pub r#type: Option<SignatureType>,
    pub index: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::spark_transaction::Entity",
        from = "Column::TxHash",
        to = "super::spark_transaction::Column::TxHash",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SparkTransaction,
}

impl Related<super::spark_transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SparkTransaction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
