"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import rpc.v1.types_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SendSparkTxRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDENTITY_PUBLIC_KEY_FIELD_NUMBER: builtins.int
    FINAL_TOKEN_TRANSACTION_FIELD_NUMBER: builtins.int
    identity_public_key: builtins.bytes
    @property
    def final_token_transaction(self) -> rpc.v1.types_pb2.TokenTransaction: ...
    def __init__(
        self,
        *,
        identity_public_key: builtins.bytes = ...,
        final_token_transaction: rpc.v1.types_pb2.TokenTransaction | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "final_token_transaction", b"final_token_transaction"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "final_token_transaction",
            b"final_token_transaction",
            "identity_public_key",
            b"identity_public_key",
        ],
    ) -> None: ...

global___SendSparkTxRequest = SendSparkTxRequest

@typing.final
class SendSparkSignatureRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SIGNATURE_DATA_FIELD_NUMBER: builtins.int
    @property
    def signature_data(self) -> rpc.v1.types_pb2.SparkSignatureData: ...
    def __init__(
        self,
        *,
        signature_data: rpc.v1.types_pb2.SparkSignatureData | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["signature_data", b"signature_data"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["signature_data", b"signature_data"]
    ) -> None: ...

global___SendSparkSignatureRequest = SendSparkSignatureRequest

@typing.final
class GetSparkTxRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FINAL_TOKEN_TRANSACTION_HASH_FIELD_NUMBER: builtins.int
    final_token_transaction_hash: builtins.bytes
    def __init__(
        self,
        *,
        final_token_transaction_hash: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "final_token_transaction_hash", b"final_token_transaction_hash"
        ],
    ) -> None: ...

global___GetSparkTxRequest = GetSparkTxRequest

@typing.final
class VerifySparkTxRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FINAL_TOKEN_TRANSACTION_FIELD_NUMBER: builtins.int
    @property
    def final_token_transaction(self) -> rpc.v1.types_pb2.TokenTransaction: ...
    def __init__(
        self,
        *,
        final_token_transaction: rpc.v1.types_pb2.TokenTransaction | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "final_token_transaction", b"final_token_transaction"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "final_token_transaction", b"final_token_transaction"
        ],
    ) -> None: ...

global___VerifySparkTxRequest = VerifySparkTxRequest

@typing.final
class ListSparkTxsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    page_token: builtins.bytes
    page_size: builtins.int
    def __init__(
        self,
        *,
        page_token: builtins.bytes | None = ...,
        page_size: builtins.int | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_page_size",
            b"_page_size",
            "_page_token",
            b"_page_token",
            "page_size",
            b"page_size",
            "page_token",
            b"page_token",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_page_size",
            b"_page_size",
            "_page_token",
            b"_page_token",
            "page_size",
            b"page_size",
            "page_token",
            b"page_token",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_page_size", b"_page_size"]
    ) -> typing.Literal["page_size"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_page_token", b"_page_token"]
    ) -> typing.Literal["page_token"] | None: ...

global___ListSparkTxsRequest = ListSparkTxsRequest

@typing.final
class VerifySparkTxResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IS_VALID_FIELD_NUMBER: builtins.int
    is_valid: builtins.bool
    def __init__(
        self,
        *,
        is_valid: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["is_valid", b"is_valid"]
    ) -> None: ...

global___VerifySparkTxResponse = VerifySparkTxResponse

@typing.final
class ListSparkTxsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_TRANSACTIONS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.bytes
    @property
    def token_transactions(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        rpc.v1.types_pb2.TokenTransactionResponse
    ]: ...
    def __init__(
        self,
        *,
        token_transactions: (
            collections.abc.Iterable[rpc.v1.types_pb2.TokenTransactionResponse] | None
        ) = ...,
        next_page_token: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_next_page_token",
            b"_next_page_token",
            "next_page_token",
            b"next_page_token",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_next_page_token",
            b"_next_page_token",
            "next_page_token",
            b"next_page_token",
            "token_transactions",
            b"token_transactions",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["_next_page_token", b"_next_page_token"]
    ) -> typing.Literal["next_page_token"] | None: ...

global___ListSparkTxsResponse = ListSparkTxsResponse

@typing.final
class GetSparkTxResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FINAL_TOKEN_TRANSACTION_FIELD_NUMBER: builtins.int
    @property
    def final_token_transaction(self) -> rpc.v1.types_pb2.TokenTransaction: ...
    def __init__(
        self,
        *,
        final_token_transaction: rpc.v1.types_pb2.TokenTransaction | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "final_token_transaction", b"final_token_transaction"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "final_token_transaction", b"final_token_transaction"
        ],
    ) -> None: ...

global___GetSparkTxResponse = GetSparkTxResponse
