# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/v1/service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lrc20.protos.rpc.v1 import types_pb2 as rpc_dot_v1_dot_types__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14rpc/v1/service.proto\x12\x06rpc.v1\x1a\x12rpc/v1/types.proto\x1a\x1bgoogle/protobuf/empty.proto"l\n\x12SendSparkTxRequest\x12\x1b\n\x13identity_public_key\x18\x01 \x01(\x0c\x12\x39\n\x17\x66inal_token_transaction\x18\x02 \x01(\x0b\x32\x18.rpc.v1.TokenTransaction"O\n\x19SendSparkSignatureRequest\x12\x32\n\x0esignature_data\x18\x01 \x01(\x0b\x32\x1a.rpc.v1.SparkSignatureData"9\n\x11GetSparkTxRequest\x12$\n\x1c\x66inal_token_transaction_hash\x18\x01 \x01(\x0c"Q\n\x14VerifySparkTxRequest\x12\x39\n\x17\x66inal_token_transaction\x18\x01 \x01(\x0b\x32\x18.rpc.v1.TokenTransaction"c\n\x13ListSparkTxsRequest\x12\x17\n\npage_token\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x12\x16\n\tpage_size\x18\x02 \x01(\rH\x01\x88\x01\x01\x42\r\n\x0b_page_tokenB\x0c\n\n_page_size")\n\x15VerifySparkTxResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08"\x86\x01\n\x14ListSparkTxsResponse\x12<\n\x12token_transactions\x18\x01 \x03(\x0b\x32 .rpc.v1.TokenTransactionResponse\x12\x1c\n\x0fnext_page_token\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x42\x12\n\x10_next_page_token"O\n\x12GetSparkTxResponse\x12\x39\n\x17\x66inal_token_transaction\x18\x01 \x01(\x0b\x32\x18.rpc.v1.TokenTransaction2\x80\x03\n\x0cSparkService\x12\x41\n\x0bSendSparkTx\x12\x1a.rpc.v1.SendSparkTxRequest\x1a\x16.google.protobuf.Empty\x12O\n\x12SendSparkSignature\x12!.rpc.v1.SendSparkSignatureRequest\x1a\x16.google.protobuf.Empty\x12I\n\x0cListSparkTxs\x12\x1b.rpc.v1.ListSparkTxsRequest\x1a\x1c.rpc.v1.ListSparkTxsResponse\x12\x43\n\nGetSparkTx\x12\x19.rpc.v1.GetSparkTxRequest\x1a\x1a.rpc.v1.GetSparkTxResponse\x12L\n\rVerifySparkTx\x12\x1c.rpc.v1.VerifySparkTxRequest\x1a\x1d.rpc.v1.VerifySparkTxResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "rpc.v1.service_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_SENDSPARKTXREQUEST"]._serialized_start = 81
    _globals["_SENDSPARKTXREQUEST"]._serialized_end = 189
    _globals["_SENDSPARKSIGNATUREREQUEST"]._serialized_start = 191
    _globals["_SENDSPARKSIGNATUREREQUEST"]._serialized_end = 270
    _globals["_GETSPARKTXREQUEST"]._serialized_start = 272
    _globals["_GETSPARKTXREQUEST"]._serialized_end = 329
    _globals["_VERIFYSPARKTXREQUEST"]._serialized_start = 331
    _globals["_VERIFYSPARKTXREQUEST"]._serialized_end = 412
    _globals["_LISTSPARKTXSREQUEST"]._serialized_start = 414
    _globals["_LISTSPARKTXSREQUEST"]._serialized_end = 513
    _globals["_VERIFYSPARKTXRESPONSE"]._serialized_start = 515
    _globals["_VERIFYSPARKTXRESPONSE"]._serialized_end = 556
    _globals["_LISTSPARKTXSRESPONSE"]._serialized_start = 559
    _globals["_LISTSPARKTXSRESPONSE"]._serialized_end = 693
    _globals["_GETSPARKTXRESPONSE"]._serialized_start = 695
    _globals["_GETSPARKTXRESPONSE"]._serialized_end = 774
    _globals["_SPARKSERVICE"]._serialized_start = 777
    _globals["_SPARKSERVICE"]._serialized_end = 1161
# @@protoc_insertion_point(module_scope)
