"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SparkSignatureData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SPARK_OPERATOR_SIGNATURE_FIELD_NUMBER: builtins.int
    SPARK_OPERATOR_IDENTITY_PUBLIC_KEY_FIELD_NUMBER: builtins.int
    LEAVES_TO_SPEND_DATA_FIELD_NUMBER: builtins.int
    FINAL_TOKEN_TRANSACTION_FIELD_NUMBER: builtins.int
    spark_operator_signature: builtins.bytes
    spark_operator_identity_public_key: builtins.bytes
    @property
    def leaves_to_spend_data(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___SparkSignatureLeafData
    ]: ...
    @property
    def final_token_transaction(self) -> global___TokenTransaction: ...
    def __init__(
        self,
        *,
        spark_operator_signature: builtins.bytes = ...,
        spark_operator_identity_public_key: builtins.bytes = ...,
        leaves_to_spend_data: (
            collections.abc.Iterable[global___SparkSignatureLeafData] | None
        ) = ...,
        final_token_transaction: global___TokenTransaction | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "final_token_transaction", b"final_token_transaction"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "final_token_transaction",
            b"final_token_transaction",
            "leaves_to_spend_data",
            b"leaves_to_spend_data",
            "spark_operator_identity_public_key",
            b"spark_operator_identity_public_key",
            "spark_operator_signature",
            b"spark_operator_signature",
        ],
    ) -> None: ...

global___SparkSignatureData = SparkSignatureData

@typing.final
class SparkSignatureLeafData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SPENT_LEAF_INDEX_FIELD_NUMBER: builtins.int
    REVOCATION_PRIVATE_KEY_FIELD_NUMBER: builtins.int
    spent_leaf_index: builtins.int
    revocation_private_key: builtins.bytes
    def __init__(
        self,
        *,
        spent_leaf_index: builtins.int = ...,
        revocation_private_key: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_revocation_private_key",
            b"_revocation_private_key",
            "revocation_private_key",
            b"revocation_private_key",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_revocation_private_key",
            b"_revocation_private_key",
            "revocation_private_key",
            b"revocation_private_key",
            "spent_leaf_index",
            b"spent_leaf_index",
        ],
    ) -> None: ...
    def WhichOneof(
        self,
        oneof_group: typing.Literal[
            "_revocation_private_key", b"_revocation_private_key"
        ],
    ) -> typing.Literal["revocation_private_key"] | None: ...

global___SparkSignatureLeafData = SparkSignatureLeafData

@typing.final
class TokenLeafToCreate(google.protobuf.message.Message):
    """This proto is constructed by the wallet to specify leaves it wants to create
    as part of a token transaction.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    OWNER_PUBLIC_KEY_FIELD_NUMBER: builtins.int
    REVOCATION_PUBLIC_KEY_FIELD_NUMBER: builtins.int
    WITHDRAWAL_BOND_SATS_FIELD_NUMBER: builtins.int
    WITHDRAWAL_LOCKTIME_FIELD_NUMBER: builtins.int
    TOKEN_PUBLIC_KEY_FIELD_NUMBER: builtins.int
    TOKEN_AMOUNT_FIELD_NUMBER: builtins.int
    id: builtins.str
    owner_public_key: builtins.bytes
    revocation_public_key: builtins.bytes
    withdrawal_bond_sats: builtins.int
    withdrawal_locktime: builtins.int
    token_public_key: builtins.bytes
    """Public key representing the token."""
    token_amount: builtins.bytes
    """Amount of tokens contained within this leaf (uint128)."""
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        owner_public_key: builtins.bytes = ...,
        revocation_public_key: builtins.bytes = ...,
        withdrawal_bond_sats: builtins.int = ...,
        withdrawal_locktime: builtins.int = ...,
        token_public_key: builtins.bytes = ...,
        token_amount: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "id",
            b"id",
            "owner_public_key",
            b"owner_public_key",
            "revocation_public_key",
            b"revocation_public_key",
            "token_amount",
            b"token_amount",
            "token_public_key",
            b"token_public_key",
            "withdrawal_bond_sats",
            b"withdrawal_bond_sats",
            "withdrawal_locktime",
            b"withdrawal_locktime",
        ],
    ) -> None: ...

global___TokenLeafToCreate = TokenLeafToCreate

@typing.final
class TokenTransaction(google.protobuf.message.Message):
    """This proto is deterministically hashed to generate the token_transaction_hash that
    is cooperatively signed by the SO group to confirm a token transaction.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUE_INPUT_FIELD_NUMBER: builtins.int
    TRANSFER_INPUT_FIELD_NUMBER: builtins.int
    LEAVES_TO_CREATE_FIELD_NUMBER: builtins.int
    SPARK_OPERATOR_IDENTITY_PUBLIC_KEYS_FIELD_NUMBER: builtins.int
    @property
    def issue_input(self) -> global___IssueInput: ...
    @property
    def transfer_input(self) -> global___TransferInput: ...
    @property
    def leaves_to_create(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___TokenLeafToCreate
    ]: ...
    @property
    def spark_operator_identity_public_keys(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        builtins.bytes
    ]: ...
    def __init__(
        self,
        *,
        issue_input: global___IssueInput | None = ...,
        transfer_input: global___TransferInput | None = ...,
        leaves_to_create: (
            collections.abc.Iterable[global___TokenLeafToCreate] | None
        ) = ...,
        spark_operator_identity_public_keys: (
            collections.abc.Iterable[builtins.bytes] | None
        ) = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "issue_input",
            b"issue_input",
            "token_input",
            b"token_input",
            "transfer_input",
            b"transfer_input",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "issue_input",
            b"issue_input",
            "leaves_to_create",
            b"leaves_to_create",
            "spark_operator_identity_public_keys",
            b"spark_operator_identity_public_keys",
            "token_input",
            b"token_input",
            "transfer_input",
            b"transfer_input",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["token_input", b"token_input"]
    ) -> typing.Literal["issue_input", "transfer_input"] | None: ...

global___TokenTransaction = TokenTransaction

@typing.final
class TransferInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEAVES_TO_SPEND_FIELD_NUMBER: builtins.int
    @property
    def leaves_to_spend(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___TokenLeafToSpend
    ]: ...
    def __init__(
        self,
        *,
        leaves_to_spend: (
            collections.abc.Iterable[global___TokenLeafToSpend] | None
        ) = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["leaves_to_spend", b"leaves_to_spend"]
    ) -> None: ...

global___TransferInput = TransferInput

@typing.final
class IssueInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUER_PUBLIC_KEY_FIELD_NUMBER: builtins.int
    issuer_public_key: builtins.bytes
    def __init__(
        self,
        *,
        issuer_public_key: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["issuer_public_key", b"issuer_public_key"]
    ) -> None: ...

global___IssueInput = IssueInput

@typing.final
class TokenLeafToSpend(google.protobuf.message.Message):
    """This proto is constructed by the wallet (without a revocation private key initially)
    to specify leaves it wants to spend as part of a token transaction. Upon sending
    the private key field will be filled and returned by the Coordinator SO so that the
    wallet can validate the full transaction hash before finalizng the transaction.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PREV_TOKEN_TRANSACTION_HASH_FIELD_NUMBER: builtins.int
    PREV_TOKEN_TRANSACTION_LEAF_VOUT_FIELD_NUMBER: builtins.int
    prev_token_transaction_hash: builtins.bytes
    prev_token_transaction_leaf_vout: builtins.int
    def __init__(
        self,
        *,
        prev_token_transaction_hash: builtins.bytes = ...,
        prev_token_transaction_leaf_vout: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "prev_token_transaction_hash",
            b"prev_token_transaction_hash",
            "prev_token_transaction_leaf_vout",
            b"prev_token_transaction_leaf_vout",
        ],
    ) -> None: ...

global___TokenLeafToSpend = TokenLeafToSpend

@typing.final
class TokenTransactionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FINALIZED_FIELD_NUMBER: builtins.int
    FINAL_TOKEN_TRANSACTION_FIELD_NUMBER: builtins.int
    finalized: builtins.bool
    @property
    def final_token_transaction(self) -> global___TokenTransaction: ...
    def __init__(
        self,
        *,
        finalized: builtins.bool = ...,
        final_token_transaction: global___TokenTransaction | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "final_token_transaction", b"final_token_transaction"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "final_token_transaction",
            b"final_token_transaction",
            "finalized",
            b"finalized",
        ],
    ) -> None: ...

global___TokenTransactionResponse = TokenTransactionResponse
