# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/v1/types.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12rpc/v1/types.proto\x12\x06rpc.v1"\xdb\x01\n\x12SparkSignatureData\x12 \n\x18spark_operator_signature\x18\x01 \x01(\x0c\x12*\n"spark_operator_identity_public_key\x18\x02 \x01(\x0c\x12<\n\x14leaves_to_spend_data\x18\x03 \x03(\x0b\x32\x1e.rpc.v1.SparkSignatureLeafData\x12\x39\n\x17\x66inal_token_transaction\x18\x04 \x01(\x0b\x32\x18.rpc.v1.TokenTransaction"r\n\x16SparkSignatureLeafData\x12\x18\n\x10spent_leaf_index\x18\x01 \x01(\r\x12#\n\x16revocation_private_key\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x42\x19\n\x17_revocation_private_key"\xc3\x01\n\x11TokenLeafToCreate\x12\n\n\x02id\x18\x01 \x01(\t\x12\x18\n\x10owner_public_key\x18\x02 \x01(\x0c\x12\x1d\n\x15revocation_public_key\x18\x03 \x01(\x0c\x12\x1c\n\x14withdrawal_bond_sats\x18\x04 \x01(\x04\x12\x1b\n\x13withdrawal_locktime\x18\x05 \x01(\x04\x12\x18\n\x10token_public_key\x18\x06 \x01(\x0c\x12\x14\n\x0ctoken_amount\x18\x07 \x01(\x0c"\xdf\x01\n\x10TokenTransaction\x12)\n\x0bissue_input\x18\x01 \x01(\x0b\x32\x12.rpc.v1.IssueInputH\x00\x12/\n\x0etransfer_input\x18\x02 \x01(\x0b\x32\x15.rpc.v1.TransferInputH\x00\x12\x33\n\x10leaves_to_create\x18\x03 \x03(\x0b\x32\x19.rpc.v1.TokenLeafToCreate\x12+\n#spark_operator_identity_public_keys\x18\x04 \x03(\x0c\x42\r\n\x0btoken_input"B\n\rTransferInput\x12\x31\n\x0fleaves_to_spend\x18\x01 \x03(\x0b\x32\x18.rpc.v1.TokenLeafToSpend"\'\n\nIssueInput\x12\x19\n\x11issuer_public_key\x18\x01 \x01(\x0c"a\n\x10TokenLeafToSpend\x12#\n\x1bprev_token_transaction_hash\x18\x01 \x01(\x0c\x12(\n prev_token_transaction_leaf_vout\x18\x02 \x01(\r"h\n\x18TokenTransactionResponse\x12\x11\n\tfinalized\x18\x01 \x01(\x08\x12\x39\n\x17\x66inal_token_transaction\x18\x02 \x01(\x0b\x32\x18.rpc.v1.TokenTransactionb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "rpc.v1.types_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_SPARKSIGNATUREDATA"]._serialized_start = 31
    _globals["_SPARKSIGNATUREDATA"]._serialized_end = 250
    _globals["_SPARKSIGNATURELEAFDATA"]._serialized_start = 252
    _globals["_SPARKSIGNATURELEAFDATA"]._serialized_end = 366
    _globals["_TOKENLEAFTOCREATE"]._serialized_start = 369
    _globals["_TOKENLEAFTOCREATE"]._serialized_end = 564
    _globals["_TOKENTRANSACTION"]._serialized_start = 567
    _globals["_TOKENTRANSACTION"]._serialized_end = 790
    _globals["_TRANSFERINPUT"]._serialized_start = 792
    _globals["_TRANSFERINPUT"]._serialized_end = 858
    _globals["_ISSUEINPUT"]._serialized_start = 860
    _globals["_ISSUEINPUT"]._serialized_end = 899
    _globals["_TOKENLEAFTOSPEND"]._serialized_start = 901
    _globals["_TOKENLEAFTOSPEND"]._serialized_end = 998
    _globals["_TOKENTRANSACTIONRESPONSE"]._serialized_start = 1000
    _globals["_TOKENTRANSACTIONRESPONSE"]._serialized_end = 1104
# @@protoc_insertion_point(module_scope)
